/* Wires a folder of part photos into the catalogue.
 *
 *   1. drop image files into  img/
 *   2. name each one after the part number or the part id, e.g.
 *        img/23100-K36-J01.jpg
 *        img/23100K36J01.png       (dashes optional)
 *        img/p005.webp             (part id also works)
 *   3. node import-images.js
 *
 * Writes images.js — a plain id -> path map that art.js reads. data.js is
 * never modified, so re-running is safe and deleting an image just drops
 * that entry and the schematic drawing comes back.
 *
 * Only use images you have the right to publish. Manufacturer catalogue
 * photography is copyrighted; a sales territory does not by itself grant a
 * licence. Your own photographs always work.
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const DIR = process.argv[2] || "img";
const EXT = /\.(jpe?g|png|webp|avif|gif)$/i;

const ctx = { console };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname, "data.js"), "utf8") + ";globalThis.__X={PARTS};", ctx);
const { PARTS } = ctx.__X;

const dir = path.join(__dirname, DIR);
if (!fs.existsSync(dir)) {
  console.error(`No ${DIR}/ directory. Create it and put the images there.`);
  process.exit(1);
}

const norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]/g, "");
const byKey = new Map();
for (const p of PARTS) {
  byKey.set(norm(p.oem), p);
  byKey.set(norm(p.id), p);
}

const files = fs.readdirSync(dir).filter(f => EXT.test(f));
const map = {};
const unmatched = [];

for (const f of files) {
  const stem = norm(f.replace(EXT, ""));
  const part = byKey.get(stem);
  if (part) {
    map[part.id] = `${DIR}/${f}`;
  } else {
    unmatched.push(f);
  }
}

const lines = Object.entries(map)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, p]) => `  ${id}: ${JSON.stringify(p)},`);

fs.writeFileSync(
  path.join(__dirname, "images.js"),
  `/* Generated by import-images.js — do not edit by hand.\n` +
  `   Re-run after adding or removing files in ${DIR}/. */\n` +
  `const IMAGES = {\n${lines.join("\n")}\n};\n`
);

const covered = Object.keys(map).length;
console.log(`${files.length} image file(s) in ${DIR}/`);
console.log(`${covered} matched to parts — written to images.js`);
console.log(`${PARTS.length - covered} part(s) still using the schematic drawing`);

if (unmatched.length) {
  console.log(`\n${unmatched.length} file(s) matched no part number or id:`);
  unmatched.slice(0, 20).forEach(f => console.log(`  ${f}`));
  if (unmatched.length > 20) console.log(`  …and ${unmatched.length - 20} more`);
  console.log(`\nRename these to the part number, e.g. 23100-K36-J01.jpg`);
}
